list = [
    [
        "第一个的大额delegator A的地址",
        "A负责投票的val1地址",
        "A负责投票的val2地址",
    ],
    [
        "第二个的大额delegator B的地址",
        "B负责投票的val1地址",
        "B负责投票的val1地址",
    ],
    [
        "第三个的大额delegator C的地址",
        "C负责投票的val1地址",
        "C负责投票的val1地址",
    ],
]