domination_percentage = "0.74"

# 18 target validators
target_validator_addresses = [
    "okexchain1q9nct2gska2yutx24starv6s63xz022fuzvv96",
    "okexchain1qva0ejf0t943x6rt824gwmvtjgec9cjrd84253",
    "okexchain1zza3jrylyecrtuh0p9ts2xauzsefuvwaynydhs",
    "okexchain1zxthrcdcecfe5ss4tal0tq30hzel2lkstd3csd",
    "okexchain1ygcvtcqxl82xvzrq25dymam434k3nnc88zd83d",
    "okexchain19wln93k3faq7vkqzlc9gljr3ey5fljt9q7gzhj",
    "okexchain195ez67wmhprwrru34gvttyd8ttpl7edxqd8rmt",
    "okexchain1xkl5agjzqnjnptyat2dng2asmx8g5kllej8eu6",
    "okexchain18v23ln9ycrtg0mrwsm004sh4tdknudtdvdedlk",
    "okexchain1g3a6vtau2k93n4tqgqnrggeu3qa4x20reu5zjx",
    "okexchain1fymxn4gazxzjdfvwvr0ccnrnjpwmj0r9azs0dj",
    "okexchain1tkwxgcpvptua0q0h5tn0at58ufnjdue7hdyksr",
    "okexchain1s6nfs7mlj7ewsskkrmekqhpq2w234fcz9sp3uz",
    "okexchain1ja9xngm4zh0t442mse73ll30p7dczd49ptxhds",
    "okexchain1508d7eq592kg2lh9d46xvv3r4sm7gm8w7lza4q",
    "okexchain1ka92ujcwh6hyyeu4tymzy3dedgxplt4d6uz6pp",
    "okexchain1c34s7lc7ec8gs9xrtxeh0j2wjaam25c3ermzx8",
    "okexchain1m569cfenudxemegcf4mmykhugnslhdv0hmdu4v",
]

# 18 workers
workers_infos = [
    "okexchain1v9asy9x82lk7hfw27kq3pzeg2rgeeg6t5u27uv,801",
    "okexchain16p9xfn6437rz898a89zq09755ng2fdt5pqp70j,802",
    "okexchain1gln5srut8yr4da5czc6rrvwsa8t0nqr0j8py6j,803",
    "okexchain1p4fk4kehstehj9k4r0qgqmnpukcxx20c9txvg3,804",
    "okexchain1vy0d5a4rh5l42dhs39e8zhjyjapa6ym32g4f6z,805",
    "okexchain1ra6urge6c8amyjk0pln2s3aefa7ak6sf2dqqku,806",
    "okexchain139kffxgctrnydhv5ahnx86mt2mkpcxcv4zry8x,807",
    "okexchain1637p2lzdfp48x4jvtmk6a4la6nmnp0v4vzlqv5,808",
    "okexchain1eyze64nqrjqxg40w7y5l8z2rah39hpx4d3ch5m,809",
    "okexchain1xs0ndkxultgldk2dvrf7dww0q4wku3t8uzu7zp,810",
    "okexchain1zua7exxn2wpdam6rlgrcgapv7fsjrct6770cwe,811",
    "okexchain1p50urkew76a6nk0s6r0falwc0jzznpxw2clz6h,812",
    "okexchain1gs90zkfql6jzj3zer06d3zmsdj0fuxx83qtuyf,813",
    "okexchain1en33je7g67t0eh2yswyzcrwjjsfwdpa9uhedjn,814",
    "okexchain16xqmjn3z36ues8hmhtvnrve9gm3gp760rgceqw,815",
    "okexchain1fvrt05h0chp37lkyy6zq4mayd6mflaahgk6333,816",
    "okexchain19eyu8zxlhuwy9rjsz8c36m4luu0dlaryz2cv4u,817",
    "okexchain134qfmgn0p5dpffxq57zdycaepl2mtpjdmcexq9,818",
]